import time
time.sleep(1)

sleep_time = 0.2
maxlen = 40

keyboard.send_keys('cd ~/Code/absolutely_vishus/screenshots/languages\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-16) + 'cd c\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-20) + 'cd ../cobol\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../crystal\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-26) + 'cd ../dart\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-23) + 'cd ../dotnet\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-26) + 'cd ../elixir\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../elm\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-22) + 'cd ../erlang\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../go\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-21) + 'cd ../haskell\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-26) + 'cd ../java\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-23) + 'cd ../julia\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../kotlin\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../lang-lua\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-27) + 'cd ../nim\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-22) + 'cd ../nodejs\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../ocaml\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../perl\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../php\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-23) + 'cd ../python\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-25) + 'cd ../r\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-20) + 'cd ../red\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-23) + 'cd ../ruby\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-23) + 'cd ../rust\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../scala\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../swift\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-24) + 'cd ../v\n')
time.sleep(sleep_time)
keyboard.send_keys(' ' * (maxlen-20) + 'cd ../zig\n')
time.sleep(sleep_time)

